# Generated by Django 4.0.2 on 2022-02-02 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AffirmativeAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.IntegerField(choices=[(0, 'да'), (1, 'конечно'), (2, 'ага'), (3, 'пожалуй')], verbose_name='Вариант утвердительного ответа')),
            ],
        ),
        migrations.CreateModel(
            name='NegativeAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.IntegerField(choices=[(0, 'нет'), (1, 'нет, конечно'), (2, 'ноуп'), (3, 'найн')], verbose_name='Вариант отрицательного ответа')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_question', models.CharField(max_length=512, verbose_name='Текст вопроса')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guessed_cat_count', models.IntegerField(default=0, verbose_name='Сколько раз загадан кот')),
                ('guessed_bread_count', models.IntegerField(default=0, verbose_name='Cколько раз загадан хлеб')),
                ('current_stage', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='QuestionStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField(default=1, verbose_name='Номер этапа')),
                ('answer_type', models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], max_length=3, null=True)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='firstapp.question')),
            ],
        ),
        migrations.CreateModel(
            name='DialogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affirmative_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.affirmativeanswer')),
                ('negative_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.negativeanswer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.user')),
            ],
            options={
                'verbose_name': 'Диалог',
                'verbose_name_plural': 'Диалоги',
            },
        ),
    ]
