# Generated by Django 4.0.2 on 2022-02-01 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AffirmativeAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.IntegerField(choices=[(0, 'конечно'), (1, 'ага'), (2, 'пожалуй')], verbose_name='Вариант утвердительного ответа')),
            ],
        ),
        migrations.CreateModel(
            name='NegativeAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.IntegerField(choices=[(0, 'нет, конечно'), (1, 'ноуп'), (2, 'найн')], verbose_name='Вариант отрицательного ответа')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_question', models.CharField(max_length=512, verbose_name='Текст вопроса')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guessed_cat_count', models.IntegerField(default=0, verbose_name='Сколько раз загадан кот')),
                ('guessed_bread_count', models.IntegerField(default=0, verbose_name='Cколько раз загадан хлеб')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='DialogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affirmative_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.affirmativeanswer')),
                ('negative_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.negativeanswer')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.question')),
            ],
        ),
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dialog_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.dialogitem')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.user')),
            ],
        ),
    ]
