# Generated by Django 4.0.2 on 2022-02-02 14:09

from django.db import migrations

def forward_code(apps, se):
    text_questions = [
        'Привет! Я помогу отличить кота от хлеба! Объект перед тобой квадратный?',
        'У него есть уши?',
        'Это кот, а не хлеб! Не ешь его!',
        'Это хлеб, а не кот! Ешь его!'
    ]
    Question = apps.get_model('firstapp', 'Question')
    [Question.objects.get_or_create(text_question=i) for i in text_questions]

    QuestionStep = apps.get_model('firstapp', 'QuestionStep')
    QuestionStep.objects.get_or_create(question=Question.objects.get(pk=1), step=1)
    QuestionStep.objects.get_or_create(question=Question.objects.get(pk=3), step=2, answer_type='no')
    QuestionStep.objects.get_or_create(question=Question.objects.get(pk=2), step=2, answer_type='yes')
    QuestionStep.objects.get_or_create(question=Question.objects.get(pk=3), step=3, answer_type='yes')
    QuestionStep.objects.get_or_create(question=Question.objects.get(pk=4), step=3, answer_type='no')



def reverse_code(apps, se):
    Question = apps.get_model('firstapp', 'Question')
    Question.objects.all().delete()

    QuestionStep = apps.get_model('firstapp', 'QuestionStep')
    QuestionStep.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(code=forward_code, reverse_code=reverse_code)
    ]
