# Generated by Django 4.0.2 on 2022-02-01 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialogitem',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='firstapp.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='affirmativeanswer',
            name='answer',
            field=models.IntegerField(choices=[(0, 'да'), (1, 'конечно'), (2, 'ага'), (3, 'пожалуй')], verbose_name='Вариант утвердительного ответа'),
        ),
        migrations.AlterField(
            model_name='negativeanswer',
            name='answer',
            field=models.IntegerField(choices=[(0, 'нет'), (1, 'нет, конечно'), (2, 'ноуп'), (3, 'найн')], verbose_name='Вариант отрицательного ответа'),
        ),
        migrations.DeleteModel(
            name='Dialog',
        ),
    ]
