# Generated by Django 4.0.2 on 2022-02-02 06:59

from django.db import migrations, models
import firstapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_dialogitem_user_id_alter_affirmativeanswer_answer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_type', models.IntegerField(choices=[(0, firstapp.models.AffirmativeAnswer), (1, firstapp.models.NegativeAnswer)], verbose_name='Тип ответа')),
            ],
        ),
    ]
