# Generated by Django 4.0.2 on 2022-02-02 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_hitcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_stage',
            field=models.IntegerField(default=1),
        ),
    ]
