# Generated by Django 4.0.2 on 2022-02-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_user_current_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionstep',
            name='answer_type',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=3),
            preserve_default=False,
        ),
    ]
