# Generated by Django 4.0.2 on 2022-02-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_questionstep_answer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionstep',
            name='answer_type',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], max_length=3, null=True),
        ),
    ]
